services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\RequestLogger\:
    resource: '../src/*'

  Cpsit\RequestLogger\Middleware\LoggerMiddleware:
    public: true
